# Generated by Django 5.2.15 on 2026-07-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_center_code_invoice_debit_brought_forward_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicededuction',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoiceextraitem',
            options={'ordering': ['created_at']},
        ),
    ]
