# Generated by Django 5.2.15 on 2026-06-28 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centres', '0001_initial'),
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('child_limit', models.PositiveIntegerField(default=12)),
                ('age_from', models.PositiveIntegerField(default=0)),
                ('age_to', models.PositiveIntegerField(default=5)),
                ('age_unit', models.CharField(choices=[('months', 'Months'), ('years', 'Years')], default='years', max_length=10)),
                ('duration_hours', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('color_bg', models.CharField(default='#e0f2fe', max_length=20)),
                ('color_text', models.CharField(default='#0369a1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='centres.centre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SessionSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], max_length=3)),
                ('start_time', models.TimeField()),
                ('booking_type', models.CharField(choices=[('one-off', 'One-off'), ('recurring', 'Recurring')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('starting_month', models.PositiveIntegerField(default=1)),
                ('starting_week', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='centres.centre')),
                ('children', models.ManyToManyField(blank=True, related_name='slot_assignments', to='children.child')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='centres.room')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sessions_app.session')),
                ('teachers', models.ManyToManyField(blank=True, related_name='teaching_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
