# Generated by Django 5.2.15 on 2026-07-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_alter_centre_city_alter_centre_manager_name_and_more'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('centre', 'name')},
        ),
    ]
