# Generated by Django 5.2.15 on 2026-07-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='centre',
            name='manager_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='centre',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='centre',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='centre',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='centre',
            name='street_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
