# Generated by Django 5.2.15 on 2026-07-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_alter_centre_city_alter_centre_manager_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='max_capacity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
