# Generated by Django 5.2.15 on 2026-06-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sessions_app.session'),
        ),
        migrations.AddField(
            model_name='child',
            name='sibling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siblings', to='children.child'),
        ),
        migrations.AddField(
            model_name='childenrolment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='children.child'),
        ),
        migrations.AddField(
            model_name='childenrolment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='sessions_app.sessionslot'),
        ),
        migrations.AddField(
            model_name='contact',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='children.child'),
        ),
    ]
