# Generated by Django 5.2.15 on 2026-07-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schindia_auth', '0003_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preference',
            field=models.CharField(choices=[('all', 'All notifications'), ('milestones', 'Milestones only'), ('none', 'No email notifications')], default='all', max_length=15),
        ),
    ]
